######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 22 22:20:08 2012
######################################################################

TEMPLATE = app
TARGET = qtHiero
DESTDIR = bin
OBJECTS_DIR = build/obj
MOC_DIR = build/moc
UI_DIR = build/ui
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += src/mainwindow.ui
HEADERS += src/mainwindow.h
SOURCES += src/main.cpp src/mainwindow.cpp
QT += webkit
