######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 22 22:20:08 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += mainwindow.ui
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
QT += webkit
